### ISSUE TITLE
Add a dummy app for integration testing

### ISSUE THREAD

**Issue by dvmonroe** [dvmonroe/release-notes#45]
Can we utilize git submodule for maintaining a git log that we can test with - not sure, but will look into.

**Comment by andrewmcodes** [comment]
Not sure what you are thinking here but worth noting I made https://github.com/andrewmcodes/release-notes-demo

Needs to be updated but I was using this to test at one point

**Comment by dvmonroe** [comment]
I like it @andrewmcodes.  I think I should be able to setup a dummy rails app and add it as a submodule to this repo under tests/.  From there we'll have a git log for the dummy app that we can run some integration testing on.
