### ISSUE TITLE
raise exception on bin/release-notes failure

### ISSUE THREAD

**Issue by andrewmcodes** [dvmonroe/release-notes#52]
# Issue

If `bin/release-notes` fails, it fails silently. We should raise an exception and remove the temp file. 

## Environment

- Ruby **2.5.3**
- release-notes **Master**

## Current behavior

Gem logs generation message, creates temp file, and then fails silently. 

## Expected behavior

Rescue exception and remove temp file.

**Comment by andrewmcodes** [comment]
Thoughts? @dvmonroe

**Comment by andrewmcodes** [comment]
I’d like to play with this. I’ll try to get it done today (Friday) or this weekend.

**Comment by dvmonroe** [comment]
What would cause this to fail? The gem's code or something wrong with the application using the gem?

**Comment by andrewmcodes** [comment]
The latter. After talking together we decided the answer is better tests.
