### ISSUE TITLE
Commits that fall under two+ labels are duped 

### ISSUE THREAD

**Issue by andrewmcodes** [dvmonroe/release-notes#53]
# Issue

If my commit message has keywords that map to multiple labels, bugs and features for instance, the commit will show up under both labels in the release notes. While we agreed this was not a bug, it would be nice to include an option to enable/disable this behavior. 

The real question is what label will take preference if it does fall under multiple labels, which I believe is worth a discussion. Imo - we should honor the first label grepped.  

Brain dumping here but I think this means we will need to keep a record of the commit SHA and disallow it from being added to the release note file if it has already been added. Implementation will have a cost to performance because we will need to do some sort of check against commits already in the log and will likely be O(n) at best.

**Comment by andrewmcodes** [comment]
Assigning to you for now @dvmonroe to make sure you see this. Feel free to remove the assign after we talk and one of us can tackle it depending on who has bandwidth (which will likely be me before you)

**Comment by dvmonroe** [comment]
All great points @andrewmcodes . I think there can be a way here to check the commits we've already logged to our tmp.md file in memory as we discussed.  I think you're on a good track. Reach out if I can help.
