### ISSUE TITLE
Default force_rewrite = false is not working correctly

### ISSUE THREAD

**Issue by dvmonroe** [dvmonroe/release-notes#56]
# Issue

if force rewrite is false, we should still be updating the RELEASE_NOTES.md file

## Environment

- release-notes **Latest**

## Current behavior

force_rewrite = false is not updating the output file
## Expected behavior

force_rewrite = false should update the output file with the latest commits. Force rewrite should only be true if someone is starting over, or integrating into a new project.

**Comment by andrewmcodes** [comment]
Looks like the issue occurs because of this line in `log.rb`
```
return false unless system_log(tag_from: last_tag, label: all_labels).present?
```

Opened a PR for a fix.
