### ISSUE TITLE
ReleaseNotes 3.0.0

### ISSUE THREAD

**Issue by dvmonroe** [dvmonroe/release-notes#69]
- [x] Rewrite Git.rb as a class for maintainability
- [x] Rewrite System.rb as a class for maintainability
- [x] Abstract configuration delegations to it's own module
- [x] Fix DateFormat for readability - delegation not easily maintainable when reading code
- [x] Rewrite log.rb for readability

**Comment by andrewmcodes** [comment]
🥳

**Comment by dvmonroe** [comment]
Breaking changes (no more support for ruby < 2.5) will require a major version change.

**Comment by dvmonroe** [comment]
3.0.0 released
